### ISSUE TITLE
Use JSON type for protobuf google.protobuf.Struct

### ISSUE THREAD

**Issue by pradithya** [einride/protobuf-bigquery-go#257]
Bigquery added [native JSON support early this year](https://cloud.google.com/bigquery/docs/reference/standard-sql/json-data). It allow more flexible access to JSON data and also better cost efficiency compared to storing JSON as string. 

Is there any plan to change the column type for `google.protobuf.Struct` to JSON?

**Comment by alfredgunnar** [comment]
Solved in #268
